# Docker-Compose
# Позволяет собирать и управлять несколькими контейнерами одновременно
# В Каждой Контейнере что-то лежит (React , PostgreSQL , Redis)

# указываем какую вресию docker-compose будем использовать
version: "3.8"

# хранит наши контейнры(сервисы)
services:
  # добавляем PostrgeSQL
  # хранит название нашего блока
  postgres_db:
    # берем образ postgres для нашего текущего контейнера
    # :latest указывает что берем последнюю версью образа postgres
    image: postgres:latest
    # хранит пременные для текущей базы данных
    # укзывает что будет создаваться в базе при создании текущего контейнера 
    environment:
      # создаем пользователя подключеного к базе
      POSTGRES_USER: kondrich
      # для етого пользоватя(kondrich) создаеться пароль для входа 
      POSTGRES_PASSWORD: 1234
      # указываем имя для нашей базы данных
      POSTGRES_DB: my_test_db

    # соединяеть текущий контейнер с локальной машинной на которой етот контейнер будет работать
    # называеться маппинг портов
    ports:
      # порт локальной машины : порт текущего контейнера
      - "5432:5432"