# Docker-Compose
# Позволяет собирать и управлять несколькими контейнерами одновременно
# В каждой контенере что-то лежит (React , PostgreSQL , Redis)

# указываем какую вресию docker-compose будем использовать
version: "3.8"

# хранит наши контейнры(сервисы)
services:
  # добавялем PostrgeSQL
  # хранит название нашего контенера
  postgres_db:
    # берем образ postgres для нашего текущего контейнера
    image: postgres:latest