# Git Hub Actions 
# Файл хранит настройки для Автоматизации Кода текущего репозитория, само подлкючение Git Hub Actions к репозиторию

# name харнит название для одного нашего действия (action), когда действия будет произвоидться тогда будем видеть наш name
name: My_Name_Action

# on указвает когда будет запускаться My_Git_Hub_Action в любом push в любую ветку
# on:[push] действие запускаеться при push в любую ветку
# on: Ctrl + Space
# on: [push,pull_request] действие запускаеться при любом push в любую ветку и при любом pull из любой ветки

# действие запускаеться только при push в указаную master ветку
on:
  push:
    branches:
    - master
