# Generated by Django 5.1 on 2024-08-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django', '0002_mymodel1_my_column3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel1',
            old_name='my_column3',
            new_name='my_column4',
        ),
    ]
