# Generated by Django 5.1 on 2024-08-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django', '0003_rename_my_column3_mymodel1_my_column4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel1',
            old_name='my_column4',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='mymodel1',
            old_name='my_column1',
            new_name='my_number',
        ),
        migrations.RenameField(
            model_name='mymodel1',
            old_name='my_column2',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='mymodel2',
            name='my_column1',
        ),
        migrations.RemoveField(
            model_name='mymodel2',
            name='my_column2',
        ),
        migrations.AddField(
            model_name='mymodel2',
            name='is_published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
